translated: language-guide/pages/motoko.adoc
Japan-DfinityInfoHub/motoko pull request #5
Opened 2021-10-31 13:21 UTC by pontagon333

今回の部分では、Candid という単語は先頭大文字の英字で残してます。
かなり専門用語が多い印象です。お時間ある時に確認よろしくおねがいします！

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} コンパイラ、ドキュメント、また他のツールは、 https://github.com/dfinity/motoko[オープンソース] であり、Apache 2.0 ライセンスを得てリリースされています。コントリビュートは歓迎です。
OSSライセンスはどこからか取得するものではなく基本的には自分で設定するもの（GPLなどフォーク元に律速されるものもありますが）ですので、「得て」ではなく「のもとで」（原文のunderに寄せて）が良いのではないかと思いました🙏
```suggestion
{proglang} コンパイラ、ドキュメント、また他のツールは、 https://github.com/dfinity/motoko[オープンソース] であり、Apache 2.0 ライセンスのもとでリリースされています。コントリビュートは歓迎です。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} は、{IC} Canister スマートコントラクトへの、ネイテイブサポートを持っています。
「サポートを持っている」という表現を和らげてみましたがいかがでしょうか。
```suggestion
{proglang} は、{IC} Canister スマートコントラクトをネイテイブサポートしています。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} コンパイラー（かつ SDK ）は、Candid と呼ばれる言語に依存しないフォーマットでこのインターフェースを出力するので、Candid をサポートしている別の Canisters やブラウザ上のコードやスマートフォンアプリは、Actor のサービスを利用することができる。{proglang} コンパイラは、Candid ファイルを消費かつ生産でき、{proglang} に
修正内容ご確認ください🙏
```suggestion
{proglang} コンパイラー（かつ SDK ）は、Candid と呼ばれる言語に依存しないフォーマットでこのインターフェースを出力するので、Candid をサポートしている別の Canisters やブラウザ上のコードやスマートフォンアプリは、Actor のサービスを利用することができます。{proglang} コンパイラは、Candid ファイルを使用したり生成したりすることができ、{proglang} にシームレスに（ Candid をサポートしている）他の言語で実装された Canister と接続することを可能にします。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +例えば、以前の {proglang} の `+Counter+` Actor は、次に続く Candid インターフェースを持っています。
「上で示した」とした方が明確かなと思いました。
```suggestion
例えば、上で示した {proglang} の `+Counter+` Actor は、次に続く Candid インターフェースを持っています。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +{IC} は、作動している Canister のメモリと他のステータスも保持しています。それゆえ、Motoko Actor のステータスは、そのインメモリデータ構造も含め永久に残り続けます。Actor のステータスは、それぞれのメッセージと共に復元することや外部ストレージに保存することを明確に必要としていません。
Dapp の文脈では、state は、[ステート（あるいは状態）](https://blockchainexe.com/basic_blockchain4/)と訳すのが一般的かなと思いました。
```suggestion
{IC} は、作動している Canister のメモリと他のステートも保持しています。それゆえ、Motoko Actor のステートは、そのインメモリデータ構造も含め永久に残り続けます。Actor のステートは、それぞれのメッセージと共に復元することや外部ストレージに保存することを明確に必要としていません。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +それは、例えばより高価な導入のような中断はなく、インストールされ、_n_ 回インクリメントされ、そうしてアップグレードされます。
以下のようにするのはいかがでしょうか。to (for example) the richer implementation は、最初にデプロイした実装よりも、多機能（richer）なものを新たに実装する、ということを意訳しています：
```suggestion
インストール後に _n_ インクリメントされ、その後中断することなく、より高度な実装へとアップグレードすることができます。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +`+value+` は `stable` として宣言されていたので、現在のステータスやサービスの n はアップグレードの後でも保持されています。カウンティングは、0から再度始まるのではなく、n 回目から始まります。
上と同様です🙏
```suggestion
`+value+` は `stable` として宣言されていたので、現在のステートやサービスの n はアップグレードの後でも保持されています。カウンティングは、0から再度始まるのではなく、n 回目から始まります。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +stable な変数の使用のみでは解決できないシナリオために、{proglang} は、アップグレードの前後で即座に動作するかつ任意のステータスを静的な変数にすることを許可する、ユーザーが定義できるアップグレードフックを提供しています。
上と同様です🙏
```suggestion
stable な変数の使用のみでは解決できないシナリオために、{proglang} は、アップグレードの前後で即座に動作するかつ任意のステートを静的な変数にすることを許可する、ユーザーが定義できるアップグレードフックを提供しています。
```

2021-11-01 03:40 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +私達の目標は、 {IC} 上やニュートラル Candid インターフェースを通した他国の Canister スマートコントラクトと一緒に動作する Canister スマートコントラクトをいかなる言語でも作成できるようにすることです。
language neutral を、言語に対して中立である→言語に左右されない　と意訳しました：
```suggestion
私達の目標は、 {IC} 上や言語に左右されない Candid インターフェースを通した他国の Canister スマートコントラクトと一緒に動作する Canister スマートコントラクトをいかなる言語でも作成できるようにすることです。
```

2021-11-01 03:41 UTC, hoosan requested changes
プルリクありがとうございます！専門的な内容で大変だったかと思います🙇‍♂️
いくつかsuggestion付けましたのでご確認くださいませ。

2021-11-01 05:07 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} は、派生形、任意精度演算、またはガベージコレクションを含めた、多くの開発者の生産性を上げる機能を提供しています。
```suggestion
{proglang} は、派生型、任意精度演算、またはガベージコレクションを含めた、多くの開発者の生産性を上げる機能を提供しています。
```

2021-11-01 08:13 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +////
```suggestion

////
```

2021-11-01 09:28 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} コンパイラ、ドキュメント、また他のツールは、 https://github.com/dfinity/motoko[オープンソース] であり、Apache 2.0 ライセンスを得てリリースされています。コントリビュートは歓迎です。
なるほど確かに自分で設定するものですね、修正しときます！

2021-11-01 09:33 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} は、{IC} Canister スマートコントラクトへの、ネイテイブサポートを持っています。
確かにそちらの方が自然ですね、修正しときます！

2021-11-01 09:41 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} コンパイラー（かつ SDK ）は、Candid と呼ばれる言語に依存しないフォーマットでこのインターフェースを出力するので、Candid をサポートしている別の Canisters やブラウザ上のコードやスマートフォンアプリは、Actor のサービスを利用することができる。{proglang} コンパイラは、Candid ファイルを消費かつ生産でき、{proglang} に
「ですます」の型から崩れてましたね、直しときます。

2021-11-01 09:45 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +{proglang} コンパイラー（かつ SDK ）は、Candid と呼ばれる言語に依存しないフォーマットでこのインターフェースを出力するので、Candid をサポートしている別の Canisters やブラウザ上のコードやスマートフォンアプリは、Actor のサービスを利用することができる。{proglang} コンパイラは、Candid ファイルを消費かつ生産でき、{proglang} に
長い箇所も修正しときます！

2021-11-01 09:50 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +例えば、以前の {proglang} の `+Counter+` Actor は、次に続く Candid インターフェースを持っています。
了解です！

2021-11-01 10:04 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +{IC} は、作動している Canister のメモリと他のステータスも保持しています。それゆえ、Motoko Actor のステータスは、そのインメモリデータ構造も含め永久に残り続けます。Actor のステータスは、それぞれのメッセージと共に復元することや外部ストレージに保存することを明確に必要としていません。
ステータス(status)は、ステート(state)ではないんですね。混同してました。
修正しときます！

2021-11-01 10:12 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +`+value+` は `stable` として宣言されていたので、現在のステータスやサービスの n はアップグレードの後でも保持されています。カウンティングは、0から再度始まるのではなく、n 回目から始まります。
確認しました！

2021-11-01 10:12 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +stable な変数の使用のみでは解決できないシナリオために、{proglang} は、アップグレードの前後で即座に動作するかつ任意のステータスを静的な変数にすることを許可する、ユーザーが定義できるアップグレードフックを提供しています。
確認しました！

2021-11-01 10:25 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +それは、例えばより高価な導入のような中断はなく、インストールされ、_n_ 回インクリメントされ、そうしてアップグレードされます。
ここは完全に自分の誤訳でしたね。修飾箇所を間違えてました。 
助かりました、修正しときます！

2021-11-01 10:54 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +私達の目標は、 {IC} 上やニュートラル Candid インターフェースを通した他国の Canister スマートコントラクトと一緒に動作する Canister スマートコントラクトをいかなる言語でも作成できるようにすることです。
意訳助かります、こちらも修正しときます！

2021-11-01 11:55 UTC, pontagon333 commented
更新しました、確認よろしくお願いします！

2021-11-01 13:06 UTC, hoosan commented on doc/modules/language-guide/pages/motoko.adoc
> +stable な変数の使用のみでは解決できないシナリオために、{proglang} は、アップグレードの前後で即座に動作するかつ任意のステートを静的な変数にすることを許可する、ユーザーが定義できるアップグレードフックを提供しています。
```suggestion
stable な変数の使用のみでは解決できないシナリオのために、{proglang} は、アップグレードの前後で即座に動作するかつ任意のステートを静的な変数にすることを許可する、ユーザーが定義できるアップグレードフックを提供しています。
```

2021-11-01 13:07 UTC, hoosan approved these changes

2021-11-01 13:10 UTC, merged

2021-11-02 04:16 UTC, pontagon333 commented on doc/modules/language-guide/pages/motoko.adoc
> +stable な変数の使用のみでは解決できないシナリオために、{proglang} は、アップグレードの前後で即座に動作するかつ任意のステートを静的な変数にすることを許可する、ユーザーが定義できるアップグレードフックを提供しています。
🙇‍♂️